//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysFunc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysFunc()
        {
            this.SysFunc1 = new HashSet<SysFunc>();
            this.SysRole = new HashSet<SysRole>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OrderNumber { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> ParentFuncId { get; set; }
        public bool IsDisplay { get; set; }
        public string Icon { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> FuncType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysFunc> SysFunc1 { get; set; }
        public virtual SysFunc SysFunc2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysRole> SysRole { get; set; }
    }
}
